"""
Django settings for nexuslife project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Define o diretório base do projeto (a pasta que contém manage.py).
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Chave secreta para funções criptográficas do Django. Deve ser mantida em segredo em produção.
SECRET_KEY = 'django-insecure-z257q%knykf8y4h!0jy_7fov-6ig*)tmy!$85yh6flu#gt&c&v'

# SECURITY WARNING: don't run with debug turned on in production!
# Ativa/desativa o modo de depuração. Em produção, deve ser False.
DEBUG = True

# Lista de hosts/domínios que podem servir este site Django.
ALLOWED_HOSTS = []


# Application definition
# Lista de todos os aplicativos que o Django irá carregar.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core', # Nosso aplicativo principal.
]

# Camadas de processamento de requisição/resposta. A ordem é importante.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# O arquivo URLconf raiz do projeto.
ROOT_URLCONF = 'nexuslife.urls'

# Configurações dos templates.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Ponto de entrada para servidores compatíveis com WSGI.
WSGI_APPLICATION = 'nexuslife.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Configuração do banco de dados. Por padrão, usa SQLite.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# Validadores para fortalecer as senhas dos usuários.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
# Configurações de idioma e fuso horário.
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# URL para servir arquivos estáticos.
STATIC_URL = 'static/'
# Diretórios adicionais onde o Django procurará por arquivos estáticos.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Configurações de Login e Redirecionamento
LOGIN_URL = 'login' # Define a rota para onde usuários não autenticados são enviados
LOGIN_REDIRECT_URL = 'home' # Define para onde ir após o login com sucesso
LOGOUT_REDIRECT_URL = 'login' # Define para onde ir após o logout

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
# Tipo de campo de chave primária padrão para os modelos.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
