# Generated by Django 4.2.29 on 2026-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_address_userprofile_cep_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Novo Pedido'), ('order_updated', 'Pedido Atualizado'), ('review', 'Nova Avaliação'), ('message', 'Nova Mensagem'), ('payment', 'Pagamento'), ('service', 'Nova Vaga'), ('account', 'Conta')], max_length=20),
        ),
    ]
