# Generated by Django 4.2.29 on 2026-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_favorite_freelancerprofile_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text='Para Pessoa Jurídica', max_length=150),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Para Pessoa Jurídica', max_length=18),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='person_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
    ]
