# Generated by Django 4.2.29 on 2026-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_freelancerprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='state_registration',
            field=models.CharField(blank=True, help_text='Inscrição Estadual para PJ', max_length=20),
        ),
    ]
